FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["TrainingCenter.Gateway.csproj", "./"]
RUN dotnet restore "TrainingCenter.Gateway.csproj"

COPY . .
RUN dotnet publish "TrainingCenter.Gateway.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app

COPY --from=build /app/publish .

EXPOSE 8080

ENTRYPOINT ["dotnet", "TrainingCenter.Gateway.dll"]